# Generated by Django 3.2.6 on 2021-08-11 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 4, 4, 10, 804389, tzinfo=utc)),
        ),
    ]
